name: Build github pages docs

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

jobs:
  build-docs:
    name: Publish documentation to gh-pages
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out github
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install os dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install pandoc doxygen -y

      - name: Install dependencies (python)
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install --upgrade -r requirements-doc.txt

      - name: Install package
        run: |
          python -m pip install .

      - name: Build docs
        run: |
          cd docs/
          make html
          cd _build/html

          git init
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Rebuild docs"
          git branch -m gh-pages

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: docs/_build/html
          force: true

