name: Testing

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch: {}


jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out github
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies (python)
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install --upgrade flake8 black mypy

      - name: Run black
        run: |
          black --check .

      - name: Run flake8
        run: |
          flake8 .

      - name: Run mypy
        run: |
          mypy --strict .
